const actionTypes = {
    FORMULARIO_PROYECTO: 'FORMULARIO_PROYECTO',
    OBTENER_PROYECTOS: 'OBTENER_PROYECTOS',
    AGREGAR_PROYECTOS: 'AGREGAR_PROYECTOS',
    VALIDAR_FORMULARIO: 'VALIDAR_FORMULARIO',
    PROYECTO_ACTUAL: 'PROYECTO_ACTUAL',
    ELIMINAR_PROYECTO: 'ELIMINAR_PROYECTO',
}

export default actionTypes