const actionTypes = {
    FORMULARIO_PROYECTO: 'FORMULARIO_PROYECTO',
    OBTENER_PROYECTOS: 'OBTENER_PROYECTOS',
    AGREGAR_PROYECTOS: 'AGREGAR_PROYECTOS',
    VALIDAR_FORMULARIO: 'VALIDAR_FORMULARIO',
    PROYECTO_ACTUAL: 'PROYECTO_ACTUAL',
    ELIMINAR_PROYECTO: 'ELIMINAR_PROYECTO',

    TAREAS_PROYECTOS: 'TAREAS_PROYECTOS',
    AGREGAR_TAREAS: 'AGREGAR_TAREAS',
    VALIDAR_TAREA: 'VALIDAR_TAREA',
    ELIMINAR_TAREA: 'ELIMINAR_TAREA',
    EDITAR_TAREA: 'EDITAR_TAREA',
    GUARDAR_TAREA_ACTUAL: 'GUARDAR_TAREA_ACTUAL',
    ESTADO_TAREA: 'ESTADO_TAREA',

}

export default actionTypes